#!/bin/bash

# Fix DNS set by misguided internet routers.
# Copy this file to /etc/NetworkManager/dispatcher.d/50fix-dns
# Mark script executable.
#
# JM 12/2013

cat << EOF > /etc/resolv.conf
# DONT EDIT
# see $0

# Google public DNS:
nameserver 8.8.8.8
nameserver 8.8.4.4

EOF

